name: Integration

on:
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    depcheck:
        name: Testing Depcheck

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.4
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.26.3

            - name: Test Depcheck
              run: pnpm depcheck

    inflint:
        name: Testing Inflint

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.4
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.26.3

            - name: Test Inflint
              run: pnpm inflint

    typescript:
        name: Testing TypeScript

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.4
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.26.3

            - name: Test TypeScript
              run: pnpm type-check

    prettier:
        name: Testing Prettier

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.4
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.26.3

            - name: Test Prettier
              run: pnpm prettier

    eslint:
        name: Testing ESLint

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.4
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.26.3

            - name: Test ESLint
              run: pnpm lint

    dist:
        name: Testing dist

        runs-on: [self-hosted, Linux, X64, integration]
        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.4
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.26.3

            - name: Test dist
              run: pnpm dist
