name: Semantic Release

on:
    push:
        branches: [main]

jobs:
    release:
        name: Release version
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node environment
              uses: Exlint/node-environment@v1.2.4
              with:
                  node-version: 18.13.0
                  package-manager: pnpm
                  package-manager-version: 7.26.3

            - name: Build dist folder
              run: pnpm dist

            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@v2
              with:
                  extra_plugins: |
                      @semantic-release/changelog
                      @semantic-release/commit-analyzer
                      @semantic-release/git
                      @semantic-release/npm
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
